# Generated by Django 6.0.3 on 2026-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erudition', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
