# Generated by Django 6.0.3 on 2026-07-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erudition', '0006_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_image', models.ImageField(upload_to='team/')),
                ('employee_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'employee_name'],
            },
        ),
    ]
