# Generated by Django 6.0.3 on 2026-08-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erudition', '0007_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='Erudition.category'),
        ),
    ]
