# Generated by Django 6.0.3 on 2026-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erudition', '0012_enrollment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(default='Erudition Team', max_length=255)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
    ]
